import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

VERSION = "v3.2"

# Set up directories
root_dir = Path(__file__).parent
data_dir = root_dir / f'dat_{VERSION}'
plots_dir = root_dir / f'plot_{VERSION}'
plots_dir.mkdir(exist_ok=True)

# Define full configurations for every single .dat file generated by the solver
plot_config = {
    # --- Primary States & Control ---
    'w_total.dat': {
        'title': 'State: Total Tumor Weight w(t)',
        'xlabel': 'Time t (days)', 'ylabel': 'Weight (g)', 'color': '#1f77b4'
    },
    'u.dat': {
        'title': 'Optimal Control: Drug Dose u(t)',
        'xlabel': 'Time t (days)', 'ylabel': 'Dose (mg/kg)', 'color': '#d62728'
    },
    'q_drug.dat': {
        'title': 'State: Drug Concentration q(t)',
        'xlabel': 'Time t (days)', 'ylabel': 'Concentration', 'color': '#2ca02c'
    },

    # --- Biological Sub-Compartment Transit States ---
    'z0.dat': {
        'title': 'State: Proliferating Tumor Cells z0(t)',
        'xlabel': 'Time t (days)', 'ylabel': 'Mass (g)', 'color': '#bcbd22'
    },
    'z1.dat': {
        'title': 'State: Damaged Transit Cells z1(t)',
        'xlabel': 'Time t (days)', 'ylabel': 'Mass (g)', 'color': '#17becf'
    },
    'z2.dat': {
        'title': 'State: Damaged Transit Cells z2(t)',
        'xlabel': 'Time t (days)', 'ylabel': 'Mass (g)', 'color': '#9467bd'
    },
    'z3.dat': {
        'title': 'State: Damaged Transit Cells z3(t)',
        'xlabel': 'Time t (days)', 'ylabel': 'Mass (g)', 'color': '#e377c2'
    },

    # --- Optimality Condition ---
    'Phi.dat': {
        'title': 'Switching Condition Φ(t)',
        'xlabel': 'Time t (days)', 'ylabel': 'Φ(t)', 'color': '#1f77b4'
    },

    # --- Co-state Variables ---
    'lambda-z0.dat': {
        'title': 'Costate Variable λ_z0(t) [Proliferating Core]',
        'xlabel': 'Time t (days)', 'ylabel': 'Costate λ_z0(t)', 'color': '#ff7f0e'
    },
    'lambda-z1.dat': {
        'title': 'Costate Variable λ_z1(t) [Transit Stage 1]',
        'xlabel': 'Time t (days)', 'ylabel': 'Costate λ_z1(t)', 'color': '#8c564b'
    },
    'lambda-z2.dat': {
        'title': 'Costate Variable λ_z2(t) [Transit Stage 2]',
        'xlabel': 'Time t (days)', 'ylabel': 'Costate λ_z2(t)', 'color': '#7f7f7f'
    },
    'lambda-z3.dat': {
        'title': 'Costate Variable λ_z3(t) [Transit Stage 3]',
        'xlabel': 'Time t (days)', 'ylabel': 'Costate λ_z3(t)', 'color': '#e377c2'
    },
    'lambda-q.dat': {
        'title': 'Costate Variable λ_q(t) [Drug Toxicity]',
        'xlabel': 'Time t (days)', 'ylabel': 'Costate λ_q(t)', 'color': '#f7b6d2'
    },

    # --- Running Integral Cost Tracker ---
    'int.dat': {
        'title': 'Cumulative Cost: Integral int(t)',
        'xlabel': 'Time t (days)', 'ylabel': 'Cumulative Cost', 'color': 'purple'
    }
}

# Iterate and plot each file independently
for filename, config in plot_config.items():

    dat_file = data_dir / filename

    if not dat_file.exists():
        print(f"✗ Skipping (File not found): {filename}")
        continue

    try:
        data = np.loadtxt(dat_file)

        fig, ax = plt.subplots(figsize=(10, 5.5))

        # ==========================
        # SPECIAL CASE: u(t)
        # ==========================
        if filename == 'u.dat':

            if data.ndim == 1:
                t = np.arange(len(data))
                u = data
            else:
                t = data[:, 0]
                u = data[:, 1]

            markerline, stemlines, baseline = ax.stem(
                t, u,
                linefmt=config['color'],
                markerfmt='o',
                basefmt='k-'
            )

            plt.setp(stemlines, linewidth=2)
            plt.setp(markerline, markersize=5)

        # ==========================
        # ALL OTHER VARIABLES
        # ==========================
        else:

            if data.ndim == 1:
                ax.plot(
                    data,
                    marker='o',
                    linestyle='-',
                    linewidth=1.5,
                    markersize=1,
                    color=config['color']
                )
            else:
                ax.plot(
                    data[:, 0],
                    data[:, 1],
                    marker='o',
                    linestyle='-',
                    linewidth=1.5,
                    markersize=1,
                    color=config['color']
                )

        # Formatting
        ax.set_title(
            config['title'],
            fontsize=13,
            fontweight='bold',
            pad=12
        )

        ax.set_xlabel(config['xlabel'], fontsize=11)
        ax.set_ylabel(config['ylabel'], fontsize=11)

        ax.grid(True, linestyle=':', alpha=0.6)

        output_filename = (
            f"{filename.replace('.dat', '')}_plot_{VERSION}.png"
        )

        fig.tight_layout()

        fig.savefig(
            plots_dir / output_filename,
            dpi=200,
            bbox_inches='tight'
        )

        plt.close(fig)

        print(f"✓ Successfully Plotted: {output_filename}")

    except Exception as e:
        print(f"✗ Numerical parsing failure on {filename}: {e}")

print(f"\nAll plots saved successfully in: {plots_dir}")